//repertoryList
export const repertoryListTypes = {
    //
    LOADING_GIT_REPERTORY : 'LOADING_GIT_REPERTORY',
    SELECT_GIT_REPERTORY : 'SELECT_GIT_REPERTORY',
    CHANGE_SELECTED_ROW_KEYS: 'CHANGE_SELECTED_ROW_KEYS',
    CHANGE_SELECTED_LABEL_KEY: 'CHANGE_SELECTED_LABEL_KEY',
    CHANGE_FILTER_TEXT: 'CHANGE_FILTER_TEXT',
}

//GitRepertory
export const editRepertoryTypes = {
    //edit
    SHOW_GIT_REPERTORY: 'SHOW_GIT_REPERTORY',
    HIDE_GIT_REPERTORY: 'HIDE_GIT_REPERTORY',
    SHOW_IMPORT_REPERTORY: 'SHOW_IMPORT_REPERTORY',
    HIDE_IMPORT_REPERTORY: 'HIDE_IMPORT_REPERTORY',
}

