//GitRepertory
export const repertoryListTypes = {
    LOADING_GIT_REPERTORY : 'LOADING_GIT_REPERTORY',
    SELECT_GIT_REPERTORY : 'SELECT_GIT_REPERTORY',
    CHANGE_SELECTED_ROW_KEYS: 'CHANGE_SELECTED_ROW_KEYS',
    CHANGE_FILTER_TEXT: 'CHANGE_FILTER_TEXT',
}

